[options]
; Rutas de addons: primero los del core de Odoo, luego tus módulos custom
addons_path = D:\trabajo\Pyxel\IA\odoo17\odoo\addons,
              D:\trabajo\Pyxel\IA\odoo17\custom_addons,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\terceros,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\addons-l10n_cu,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\cubaelectronica,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\dynamic_dashboard,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\izi_dashboard,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\muk_web_theme,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\odin2,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\odin2-stock,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\odin2-userguide,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\payment_gateway_transfermovil,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\pyxel_import,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\pyxel_integracion,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\SCEM,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\seric,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\tools-l10n_cu_v17,
              D:\trabajo\Pyxel\IA\odoo17\proyectos\tools-odoo-17

; Conexión a PostgreSQL
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = erp_odin_dev

; Servidor web
http_port = 8070

; Directorio de datos (filestore, sesiones)
data_dir = D:\trabajo\Pyxel\IA\odoo17\data_dev

; Desarrollo
log_level = info
limit_time_cpu = 600
limit_time_real = 1200
