# -*- coding: utf-8 -*-
{
    "name": "Pyxel Enetradex Custom Website Theme",
    "version": "17.0.1.1.0",
    "summary": """Custom theme for Pyxel Agrimpex website with Bootstrap 4 styling""",
    "author": "Pyxel Solutions",
    "contributors": "Leudis Estrada González <leudix.rafael@gmail.com>",
    "website": "https://agrimpex.pyxelsolution.com/",
    "category": "Website",
    "depends": ["web", "website", "portal", "mass_mailing", "pyxel_import_website"],
    "data": [
        "views/layout/base_layout.xml",
        "views/components/custom_user_dropdown.xml",
        "views/components/custom_account_link.xml",
        "views/components/custom_my_account_btns.xml",
        "views/components/navbar.xml",
        "views/components/footer.xml",
        "views/components/whatsapp_widget.xml",
        "views/components/custom_breadcumb.xml",
        "views/components/portal_home.xml",
        "views/pages/home.xml",
        "views/pages/accreditation.xml",
        "views/pages/shop.xml",
        "views/pages/cart.xml",
        "views/pages/product.xml",
        "views/pages/about.xml",
        "views/pages/contactus.xml",
        "views/pages/portal_notifications.xml",
        "views/pages/my_account.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "pyxel_enetradex_custom_web_theme/static/src/scss/agrimpex_theme.scss",
            "pyxel_enetradex_custom_web_theme/static/src/scss/nosotros.scss",
            "pyxel_enetradex_custom_web_theme/static/src/scss/contactus.scss",
            "pyxel_enetradex_custom_web_theme/static/src/scss/agrimpex_redesign.scss",
            "pyxel_enetradex_custom_web_theme/static/src/scss/en_track.scss",
            "pyxel_enetradex_custom_web_theme/static/src/js/custom_scripts.js",
            "pyxel_enetradex_custom_web_theme/static/src/js/accreditation.js",
        ],
        "web.assets_backend": [
            "pyxel_enetradex_custom_web_theme/static/src/scss/agrimpex_backend.scss",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
